export type OsmTag = { key: string; value: string };

export type Industry = {
  id: string;
  label: string;
  blurb: string;
  tags: OsmTag[];
  sampleNames: string[];
};

export const INDUSTRIES: Industry[] = [
  {
    id: "painters",
    label: "Painters",
    blurb: "Exterior and interior crews still live on a Facebook album. A photo-led site books the next house.",
    tags: [{ key: "craft", value: "painter" }],
    sampleNames: [
      "Ridge Color Co.",
      "Northline Painting",
      "Cedar Brush Painters",
      "Harbor Coat & Cover",
      "Summit Finish Painting",
      "Lantern Exterior Co.",
      "True Tone Painters",
      "Oak Street Coatings",
    ],
  },
  {
    id: "landscapers",
    label: "Landscapers / lawn care",
    blurb: "Yard work sells on before/after photos. Many crews still have no site at all.",
    tags: [
      { key: "craft", value: "gardener" },
      { key: "office", value: "landscape_architect" },
    ],
    sampleNames: [
      "Greenline Landscapes",
      "Cedar Path Outdoor",
      "Wilder Gardens",
      "North Lot Lawn Co.",
      "Harbor Hedge & Lawn",
      "Ridgework Outdoor",
      "Lot Line Landscapes",
      "Amber Field Lawn Care",
    ],
  },
  {
    id: "roofers",
    label: "Roofers",
    blurb: "Storm-season searches convert if the phone and photos are one tap away.",
    tags: [{ key: "craft", value: "roofer" }],
    sampleNames: [
      "Ridge Line Roofing",
      "North Pitch Roof Co.",
      "Harbor Shingle Works",
      "Summit Deck Roofing",
      "Cedar Cap Roofers",
      "Ironwood Roofing",
      "Lantern Roof & Repair",
      "True North Roof Co.",
    ],
  },
  {
    id: "concrete",
    label: "Concrete / masonry",
    blurb: "Driveways and patios close on portfolio photos, not a Maps pin.",
    tags: [
      { key: "craft", value: "mason" },
      { key: "craft", value: "stonemason" },
      { key: "craft", value: "paver" },
    ],
    sampleNames: [
      "Stonegate Concrete",
      "North Slab Co.",
      "Harbor Masonry",
      "Ridgeform Concrete",
      "Cedar Block & Brick",
      "Summit Pour Works",
      "Lantern Stone Co.",
      "True Line Masonry",
    ],
  },
  {
    id: "fencing",
    label: "Fencing",
    blurb: "Fence quotes start online. A photo page and a number beat a Maps pin.",
    tags: [
      { key: "craft", value: "fence" },
      { key: "shop", value: "fence" },
    ],
    sampleNames: [
      "Lot Line Fence Co.",
      "Northgate Fencing",
      "Harbor Post & Rail",
      "Cedar Boundary Fencing",
      "Ridgewood Fence Works",
      "Summit Gate Co.",
      "Lantern Fence & Gate",
      "True Line Fencing",
    ],
  },
  {
    id: "electricians",
    label: "Electricians",
    blurb: "Panel upgrades and emergency calls go to whoever looks reachable on a phone.",
    tags: [{ key: "craft", value: "electrician" }],
    sampleNames: [
      "Copper Line Electric",
      "Northwire Electric",
      "Harbor Circuit Co.",
      "Summit Spark Electric",
      "Cedar Volt Works",
      "Lantern Electric",
      "True Current Co.",
      "Ridge Panel Electric",
    ],
  },
  {
    id: "plumbers",
    label: "Plumbers",
    blurb: "Emergency trades win on mobile speed. Many still have no website at all.",
    tags: [
      { key: "craft", value: "plumber" },
      { key: "shop", value: "plumbing" },
    ],
    sampleNames: [
      "True North Plumbing",
      "Blue Wren Drain Co.",
      "All-Hours Pipeworks",
      "Clearflow Plumbing",
      "Harbor Pipe Co.",
      "Summit Drain Works",
      "Cedar Line Plumbing",
      "Lantern Plumbing",
    ],
  },
  {
    id: "hvac",
    label: "HVAC",
    blurb: "Heat and AC searches are seasonal and urgent. A fast site beats a voicemail box.",
    tags: [
      { key: "craft", value: "hvac" },
      { key: "craft", value: "hvac_technician" },
    ],
    sampleNames: [
      "Rapid Coil HVAC",
      "Summit Air & Heat",
      "Lantern HVAC",
      "Northwind Mechanical",
      "Harbor Cool Co.",
      "Cedar Climate Works",
      "Ironwood Air & Heat",
      "True Temp HVAC",
    ],
  },
  {
    id: "cleaning",
    label: "Cleaning companies",
    blurb: "Recurring jobs come from a simple services page and a tap-to-book form.",
    tags: [
      { key: "craft", value: "window_cleaner" },
      { key: "craft", value: "cleaner" },
      { key: "office", value: "cleaning" },
    ],
    sampleNames: [
      "Northlight Cleaning",
      "Harbor Shine Co.",
      "Cedar Sparkle Crew",
      "Summit Clean Works",
      "Lantern Maid Co.",
      "True Line Cleaning",
      "Ridgeview Janitorial",
      "Oak Street Cleaners",
    ],
  },
  {
    id: "mobile-detailing",
    label: "Mobile detailing",
    blurb: "Mobile crews are easy to book if hours, areas, and packages are on one page.",
    tags: [
      { key: "shop", value: "car_detailing" },
      { key: "amenity", value: "car_wash" },
    ],
    sampleNames: [
      "Harbor Detail Co.",
      "Northline Mobile Shine",
      "Cedar Coat Detailing",
      "Summit Mobile Detail",
      "Lantern Auto Shine",
      "True Gloss Detailing",
      "Ridgewater Detail",
      "Oak Lot Shine Co.",
    ],
  },
  {
    id: "tree-service",
    label: "Tree service",
    blurb: "Storm work and removals go to whoever looks insured and reachable.",
    tags: [
      { key: "craft", value: "tree_surgeon" },
      { key: "craft", value: "arborist" },
    ],
    sampleNames: [
      "North Crown Tree Co.",
      "Harbor Arbor Works",
      "Cedar Canopy Service",
      "Summit Tree Care",
      "Lantern Limb Co.",
      "True Line Tree Service",
      "Ridgewood Arborists",
      "Oak & Pine Tree Co.",
    ],
  },
  {
    id: "junk-removal",
    label: "Junk removal",
    blurb: "Same-week haul-offs book from a clean page with a phone number.",
    tags: [
      { key: "office", value: "moving_company" },
      { key: "shop", value: "junk" },
    ],
    sampleNames: [
      "Clear Lot Junk Co.",
      "North Haul Removal",
      "Harbor Junk & Haul",
      "Summit Load Out",
      "Cedar Dump Run",
      "Lantern Junk Removal",
      "True Line Hauling",
      "Ridgeaway Junk Co.",
    ],
  },
  {
    id: "garage-doors",
    label: "Garage door companies",
    blurb: "Broken springs are an emergency search. A one-page site with a number wins.",
    tags: [
      { key: "shop", value: "garage_doors" },
      { key: "shop", value: "doors" },
    ],
    sampleNames: [
      "Northgate Door Co.",
      "Harbor Garage Doors",
      "Cedar Spring Works",
      "Summit Door & Opener",
      "Lantern Garage Co.",
      "True Line Doors",
      "Ridge Roll Door Co.",
      "Oak Street Openers",
    ],
  },
  {
    id: "flooring",
    label: "Flooring",
    blurb: "Showrooms still hide inventory. A photo catalog and quote form close remodels.",
    tags: [
      { key: "shop", value: "flooring" },
      { key: "craft", value: "floorer" },
      { key: "craft", value: "tiler" },
    ],
    sampleNames: [
      "Harbor Floor Co.",
      "North Plank Flooring",
      "Cedar Tile & Floor",
      "Summit Surface Works",
      "Lantern Hardwood Co.",
      "True Line Flooring",
      "Ridge Tile Co.",
      "Oak & Stone Floors",
    ],
  },
  {
    id: "handyman",
    label: "Handyman / general contractors",
    blurb: "Small jobs and remodels still get hired from a phone and a few job photos.",
    tags: [
      { key: "craft", value: "handyman" },
      { key: "craft", value: "builder" },
      { key: "office", value: "construction_company" },
    ],
    sampleNames: [
      "Hearth & Timber",
      "North Frame Builders",
      "Beacon Build Co.",
      "Lot Line Carpentry",
      "Harbor Handy Co.",
      "Summit Fix Works",
      "Cedar Task Builders",
      "Lantern General Co.",
    ],
  },
  {
    id: "pressure-washing",
    label: "Pressure washing",
    blurb: "Driveways and storefronts sell on before/after shots.",
    tags: [{ key: "craft", value: "pressure_washing" }],
    sampleNames: [
      "North Blast Wash Co.",
      "Harbor Pressure Works",
      "Cedar Jet Wash",
      "Summit Surface Wash",
      "Lantern Power Wash",
      "True Line Pressure Co.",
      "Ridge Clean Wash",
      "Oak Street Blasting",
    ],
  },
  {
    id: "auto",
    label: "Auto repair",
    blurb: "Shops with only a Google listing miss service-booking and trust pages.",
    tags: [
      { key: "shop", value: "car_repair" },
      { key: "shop", value: "car" },
      { key: "amenity", value: "vehicle_inspection" },
    ],
    sampleNames: [
      "Redline Auto Works",
      "Pioneer Garage",
      "Eastside Alignment",
      "Kestrel Motors",
      "Harbor Brake & Tire",
      "Third Street Auto",
      "Northwind Repair",
      "Copper State Garage",
    ],
  },
  {
    id: "towing",
    label: "Towing",
    blurb: "Night calls go to whoever looks open and local. A simple site beats a buried listing.",
    tags: [{ key: "amenity", value: "towing" }],
    sampleNames: [
      "North Hook Towing",
      "Harbor Tow Co.",
      "Cedar Recovery",
      "Summit Wrecker Service",
      "Lantern Towing",
      "True Line Tow Co.",
      "Ridgeway Recovery",
      "Oak Street Towing",
    ],
  },
  {
    id: "pest-control",
    label: "Pest control",
    blurb: "Seasonal pest searches convert if the quote form loads on a phone.",
    tags: [
      { key: "shop", value: "pest_control" },
      { key: "craft", value: "pest_control" },
    ],
    sampleNames: [
      "Northfield Pest Co.",
      "Harbor Bug Works",
      "Cedar Shield Pest",
      "Summit Pest Control",
      "Lantern Exterminators",
      "True Line Pest Co.",
      "Ridge Guard Pest",
      "Oak & Ant Pest Co.",
    ],
  },
  {
    id: "windows-doors",
    label: "Window / door installers",
    blurb: "Replacement jobs are high-ticket. Photos and financing notes belong on a real site.",
    tags: [
      { key: "craft", value: "window_construction" },
      { key: "shop", value: "windows" },
      { key: "shop", value: "doors" },
    ],
    sampleNames: [
      "Harbor Glass & Door",
      "Northlight Windows",
      "Cedar Frame Install",
      "Summit Pane Co.",
      "Lantern Door & Window",
      "True Line Openings",
      "Ridgeview Windows",
      "Oak Street Doors",
    ],
  },
  {
    id: "pool-service",
    label: "Pool service",
    blurb: "Weekly routes and repairs book from a clear service area page.",
    tags: [
      { key: "shop", value: "swimming_pool" },
      { key: "craft", value: "swimming_pool_installer" },
    ],
    sampleNames: [
      "Harbor Pool Co.",
      "North Blue Pool Service",
      "Cedar Water Works",
      "Summit Pool Care",
      "Lantern Aqua Service",
      "True Line Pools",
      "Ridgewater Pool Co.",
      "Oak Splash Service",
    ],
  },
  {
    id: "solar",
    label: "Solar",
    blurb: "Local installers still lose leads to national lead-gen sites.",
    tags: [
      { key: "craft", value: "solar_thermal_installer" },
      { key: "office", value: "energy_supplier" },
    ],
    sampleNames: [
      "North Sun Co.",
      "Harbor Solar Works",
      "Cedar Panel Install",
      "Summit Solar Co.",
      "Lantern Sun & Power",
      "True Line Solar",
      "Ridgevolt Solar",
      "Oak Street Solar",
    ],
  },
  {
    id: "salons",
    label: "Barbers / salons",
    blurb: "Independent shops often have no booking site — a fast, high-intent offer.",
    tags: [
      { key: "shop", value: "hairdresser" },
      { key: "shop", value: "beauty" },
      { key: "shop", value: "barber" },
    ],
    sampleNames: [
      "Goldfinch Salon",
      "Ribbon & Root",
      "The Cut Room",
      "Bramble Hair",
      "Northlight Barber",
      "Harbor Chair Co.",
      "Cedar Cut Club",
      "Lantern Barber Shop",
    ],
  },
  {
    id: "nails",
    label: "Nail salons",
    blurb: "Walk-ins still rule, but a booking page captures after-hours searches.",
    tags: [{ key: "shop", value: "nails" }],
    sampleNames: [
      "Luna Nail Bar",
      "Velvet Chair Nails",
      "Northlight Nails",
      "Harbor Polish Co.",
      "Cedar Nail Studio",
      "Summit Mani Co.",
      "Lantern Nail Bar",
      "Oak Street Nails",
    ],
  },
  {
    id: "fitness",
    label: "Gyms / personal trainers",
    blurb: "Class schedules and trial offers convert — if the site can carry them.",
    tags: [
      { key: "leisure", value: "fitness_centre" },
      { key: "leisure", value: "sports_centre" },
    ],
    sampleNames: [
      "Kiln Fitness",
      "Iron District Gym",
      "Night Shift Athletics",
      "Basecamp Training",
      "Forge Strength Club",
      "Harbor Train Co.",
      "Northline Athletics",
      "Summit Personal Training",
    ],
  },
  {
    id: "dentists",
    label: "Dentists",
    blurb: "Patients Google first. Thin or outdated clinic sites leak appointments.",
    tags: [{ key: "amenity", value: "dentist" }],
    sampleNames: [
      "Maple & Pine Dental",
      "Riverside Family Dentistry",
      "Brightline Dental",
      "Cedar Park Smiles",
      "Lakeside Orthodontics",
      "Summit Tooth Co.",
      "Elm Street Dental",
      "Harborview Dentistry",
    ],
  },
  {
    id: "realestate",
    label: "Realtors / small brokerages",
    blurb: "Agents still using template pages or Facebook-only listings.",
    tags: [{ key: "office", value: "estate_agent" }],
    sampleNames: [
      "Lantern Realty",
      "Cove & County Homes",
      "Northbird Properties",
      "Amber Field Realty",
      "Harborline Estates",
      "Pine Street Brokers",
      "Vale House Group",
      "Summit Lot Realty",
    ],
  },
];

export function getIndustry(id: string): Industry {
  return INDUSTRIES.find((item) => item.id === id) ?? INDUSTRIES[0];
}
